swagger: "0.7.5"
info:
  version: "1.0.0"
  title: Central erros
host: https://roupadesapo.herokuapp.com/
basepath: /
schemes:
  - http
consumes:
  -application/json
produces:
  -application/json
paths:
